### ISSUE TITLE
Can I clone this repo and run it on my computer?

### ISSUE THREAD

**Issue by Gianguyen1234** [madhur-taneja/Student-Management-Portal#1]

**Comment by madhur-taneja** [comment]
Hey @Gianguyen1234, feel free to clone the repo. Do you need any help with running the app?

**Comment by Gianguyen1234** [comment]
Yes. I need your help. What do I need to set up before running the app? (on VS code)

**Comment by Gianguyen1234** [comment]
Actually, I have a project about student-management with the typescript frontend. But the worst thing is I don't know much about typescript, my main field is android(kotlin) .  So, bro, I really need your help, my dl is this weekend. I feel depressed these days. Please help me to run the app.

**Comment by madhur-taneja** [comment]
> Yes. I need your help. What do I need to set up before running the app? (on VS code)

Sure, here are the steps:

### Setting up the development environment:

1. Install NodeJS v16.16.0
2. Install the latest version of MongoDB
3. Install the latest version of Maven
4. Install Java JDK11
Set up environment variables for all of these (except MongoDB) in your system. Those would include JAVA_HOME, MAVEN_HOME, M2, and NodeJS. Add them to the "Path" variable present in both User Variables and System Variables (create one if not there).

### Setting up the app:

1. Fork my repository (so that you can pull any changes I push in the future as well)
2. Clone the new forked that is created in your account (cloning my repo is not required since you can directly work on your copy of the project)
3. Check the version of Java, Maven, and Node in your system to make sure the env is set up properly

### Running the app:

1. Open MongoDB Compass and start a new connection at localhost:27017 (default port of Mongo)
    * Create a new database called `StudentLogin`
    * Create a new document inside it called `roles`
    * Add 3 roles inside it namely `ROLE_STUDENT`, `ROLE_MODERATOR` and `ROLE_ADMIN`
3. Go to Student-Management-Portal/server and run the command `mvn spring-boot:run` in cmd. This will start the backend
4. Go to Student-Management-Portal/client and run the following commands  in cmd:
    * `npm i`. 
    * `npm audit fix --force`
    * `npm start`

    This will start the frontend
5. You should be redirected to http://localhost:8081/ and be able to use the unrestricted part of the application.
6. Set up a user in the database through the `Sign Up` page. Then you would be able to log in using those credentials and use the entire application.

Let me know if you run into any issues. Good luck!

**Comment by Gianguyen1234** [comment]
Thank you very much, bro (≧▽≦)

**Comment by madhur-taneja** [comment]
> Thank you very much, bro (≧▽≦)

No problem. Closing the issue now
